version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: vitaflow_db
    restart: always
    environment:
      POSTGRES_DB: vitaflow_dev
      POSTGRES_USER: vitaflow_user
      POSTGRES_PASSWORD: vitaflow_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço da Aplicação Web Django
  web:
    build: .
    container_name: vitaflow_web
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-docker-12345
      # Conecta ao banco de dados rodando no container 'db'
      - DATABASE_URL=postgres://vitaflow_user:vitaflow_password@db:5432/vitaflow_dev
      # URL do microsserviço de notificação
      - NOTIFICATION_SERVICE_URL=http://notification:8001/notify
      # URL do microsserviço de telemedicina
      - TELEMEDICINE_SERVICE_URL=http://telemedicine:8002/generate-link
      # URL do microsserviço de prontuário
      - EHR_SERVICE_URL=http://ehr:8003/record
    depends_on:
      - db
      - notification
      - telemedicine
      - ehr

  # Microsserviço de Notificações
  notification:
    build: ./notification_service
    container_name: vitaflow_notification
    ports:
      - "8001:8001"

  # Microsserviço de Telemedicina (Jitsi)
  telemedicine:
    build: ./telemedicine_service
    container_name: vitaflow_telemedicine
    ports:
      - "8002:8002"

  # Microsserviço de Prontuário (EHR)
  ehr:
    build: ./ehr_service
    container_name: vitaflow_ehr
    ports:
      - "8003:8003"
    volumes:
      - ehr_data:/app/ehr.db

volumes:
  # Define o volume para persistir os dados do banco localmente
  postgres_data:
  ehr_data:
